variable "environment" {}
variable "amis" {}
variable "aws_region" {}
variable "key_name" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "sg_id" {}
variable "environment" {}
variable "vpc_name" {}